### ISSUE TITLE
Not Working on android

### ISSUE THREAD

**Issue by zeeshanjan82** [hypery2k/cordova-certificate-plugin#9] opened 2015-10-16 04:26 UTC
The plugin does not work on cordova android. Whenever I try to use it during my application boot. The cordova application crashes when launched on the android phone.

**Comment by escapedcat** [comment] 2015-10-16 04:49
Which Android version?
Which SDK version?
Which plugin version?

**Comment by zeeshanjan82** [comment] 2015-10-16 04:51
I am using android jelly beans and the plugin version 0.6.0

**Comment by escapedcat** [comment] 2015-10-16 05:00
Which cordova-android-platform version?
Which cordova version?

**Comment by zeeshanjan82** [comment] 2015-10-16 05:01
cordova-android 4.1.0

**Comment by ghenry22** [comment] 2015-10-16 05:49
android 4.1.1 works fine with the plugin for me
Cordova 5.3.3 for reference

**Comment by hypery2k** [comment] 2015-10-16 06:59
did you have any adb logcat data? Which cordova version are you using? Can you try to use cordoba-android 4.1.1?

**Comment by ghenry22** [comment] 2015-10-16 10:19
Also check that you have v0.6.0 of the plugin it an older version.

**Comment by zeeshanjan82** [comment] 2015-10-16 10:50
Still does not work. I have upgraded to cordova version 5.3.3 and I am using v0.6.0 of the plugin

**Comment by zeeshanjan82** [comment] 2015-10-16 10:53
I have also updated the cordova-android version to 4.1.1

**Comment by zeeshanjan82** [comment] 2015-10-16 11:00
I am not using esclipse. I am running all my commands from terminal. How can I check the adb log from terminal, which command should I use. I have connected my device to USB. When I run adb logcat command in terminal I don't see any error

**Comment by hypery2k** [comment] 2015-10-16 12:47
You Need to enable USB debugging to get it working, see http://stackoverflow.com/questions/3707880/using-adb-logcat-with-a-real-phone-and-not-the-emulator

Can you somehow share your app? Maybe sent me an email with the sources?

**Comment by zeeshanjan82** [comment] 2015-10-19 02:43
Thanks @hypery2k I really cannot email the project. I have tried many approaches but the problem still persists.

**Comment by hypery2k** [comment] 2015-10-19 06:45
Did you use any other Cordova plugin? If so please post them and the according version.

**Comment by nissarcs** [comment] 2015-10-19 09:21
Hi it not working in android am using inappbrowser plugin to show self signed certificate  url but in ios working fine a using latest android as well as cordova

**Comment by nissarcs** [comment] 2015-10-19 09:27
where i have to make this changes cordova.plugins.certificates.trustUnsecureCerts(true)  am changing 
    private boolean allowUntrusted = true; in CertificatesCordovaWebViewClient.java and  CertificatesPlugin.java file please help me out

**Comment by hypery2k** [comment] 2015-10-19 09:34
@nissarcs  you don't have to change anything in the code. just add at the plugin as told in the README and trigger changes from the app itself

**Comment by hypery2k** [comment] 2015-10-19 09:55
I cannot reproduce you're error with latest android and cordova. I've added some try catch around the plugin logic, but as it's not reproducible I've to close this issue.
You can try with the updated NPM package: https://www.npmjs.com/package/cordova-plugin-certificates

**Closed as completed by hypery2k** 2015-10-19 09:55 UTC
Labels: bug, Android

**Comment by nissarcs** [comment] 2015-10-19 12:05
Inside ondevice ready am accessing my self signed url
function onDeviceReady()
{
ref = window.open('testing/self signed url, '_blank', 'location=no','zoom=no','toolbar=no');
}

**Comment by hypery2k** [comment] 2015-10-19 12:20
@nissarcs this has nothing to do with the discussed android error here. If you're receiving errors please fill a new issue with details about you're setup
